---
title: "Tinder relationship Exploratory Analysis"
output: html_document
---

## Project title

Give your project a concise, interesting title that summarizes the entirety of your project

### Authors

Hilton Nguyen, Alexis Dimas, Mercedes Ro, & Jordan Lee Bailey.

### Date
02/24/2023
Winter 2022

### Abstract

No more than three sentences that summarize your project. Focus on the very most important aspects. For example: (1) "Our main question is .... This question is important because .... To address the question, we will ...." (2) "We are concerned with ..., because .... To address this concern, we plan to ...." (3) "Consider that .... This is important because .... Accordingly, we plan to ...."

### Keywords

Keywords:

### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

``````{r chart1, echo = FALSE, warning = FALSE, message = FALSE, code = readLines("Chart1.R"), fig.width = 10}
```

This chart was chosen to show the number of users who don't get matches to those who do and are successful in forming a relationship on Tinder. The information revealed is quite intriguing, it shows that a vast majority of users do not get matched on Tinder and those who do have little success in forming a relationship.

### Chart 2

ggplot(tinderdf, aes(x = outcome, y = count, fill = tinder_groups)) + geom_bar( stat = 'identity') + labs(title = 'Relationship sucess based on usage of Tinder')



I chose this chart show how many relationships come out of tinder. Matches are a relevant part to the app, but moreorso the important topic is longeiviety and if these matches last.


### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
